### PR TITLE
workflow to build single-file binary

### PR DESCRIPTION
**Pull request by rkonell**

### CODE REVIEW

**Comment by rkonell** [comment]
Using this workflow i was able to get github actions to build a linux and windows binary

**Comment by ThePieBandit** [comment]
I tried to do this some time ago, even building locally, and I kept hitting two problems.

1. it was not picking up tkinter properly and the UI would not work.
2. It could not make https calls because of some cert issue. 

I just tried downloading your latest artifact, and it looks like at the very least it has problem number 1. These two issues and my lack of time to debug them have been the cause of the long running scryfall data branch.

**Comment by rkonell** [comment]
Which version did you try, windows or linux?

**Comment by ThePieBandit** [comment]
Linux. I don't actually have a Windows box. (I can use my wife's to test
occasionally)

**Comment by rkonell** [comment]
Cool I can look into it, it seems pretty close.  Windows seems to work at least on my end.  I only have access to windows and macos atm but I'll spin up ubuntu on virtualbox for debugging what's wrong.  Assumptions make a terrible testing framework >_<

**Pull request closed without merging**
